BINANCE_API_KEY = ""
BINANCE_API_SECRET = ""
COINS = ["BTC","ADA","ATOM","BAT","BTT","CAKE","DASH","EOS","ETC","ICX","IOTA","NEO","OMG","ONT","QTUM","ROSE","TRX","VET","WIN","XLM"]
CURRENCY = "EUR" #Or USD
CURRENCY_SYMBOL = "€"
RICH_PRINTING = True
